w7d5/practice-for-ch-rails-goal-app-refactor-main/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:index, :show, :new, :create]
  resources :goals do
    resources :cheers, only: [:create]
  end
  resources :cheers, only: [:index]
  resources :user_comments, only: [:create]
  resources :goal_comments, only: [:create]
end

w7d5/practice-for-ch-rails-goal-app-refactor-main/app/views/shared/_cheer_button.html.erb
<form action="<%= goal_cheers_url(goal) %>" method="POST">
  <input type="hidden" name="authenticity_token" 
    value="<%= form_authenticity_token %>">
  <input type="submit" value="Cheer!">
</form>

w7d5/practice-for-ch-rails-goal-app-refactor-main/app/views/shared/_comments_form.html.erb
<% if current_user %>
  <h3>New Comment</h3>

  <%= render 'shared/errors' %>
  <% receiver = comment_type == "User" ? :recipient_id : :goal_id %>
  <% url =  comment_type == "User" ? user_comments_url : goal_comments_url %>

  <form action="<%= url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name=<%= "comment[#{receiver}]" %> value="<%= receiver_id %>">
    <label>Comment
      <textarea name="comment[body]"></textarea>
    </label>
    <input type="submit" value="Save Comment">
  </form>
<% end %>

w7d5/practice-for-ch-rails-goal-app-refactor-main/app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <div class="errors">
    <% flash[:errors].each do |msg| %>
      <p><b><%= msg %></b></p>
    <% end %>
  </div>
<% end %>

w7d5/practice-for-ch-rails-goal-app-refactor-main/app/views/shared/_goal_complete_button.html.erb
<form action="<%= goal_url(goal) %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="PUT">
  <input type="hidden" name="goal[completed]" value="<%= !goal.completed %>">
  <input type="submit" 
    value="<%= goal.completed ? 'Oops! Not yet complete.' : 'Complete' %>"
    id="goal_<%= goal.id %>_completed"
  >
</form>

w7d5/practice-for-ch-rails-goal-app-refactor-main/app/views/shared/_show_goal_basics.html.erb
<% privacy = (goal.private) ? "private" : "public" %>
<% completedness = (goal.completed) ? "Complete" : "Ongoing"%>

<li>
  <a href="<%= goal_url(goal) %>"><%= goal.title %></a>
  <p><i><%= privacy %></i></p>
  <p><i><%= completedness %></i></p>
  <br>

  <% if current_user && current_user.id == goal.author_id %>
    <%= render "shared/goal_complete_button", goal: goal %>
    <br>
    <form action="<%= goal_url(goal) %>" method="post">
        <input
          type="hidden"
          name="authenticity_token"
          value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="delete">
        <input type="submit" value="<%= "delete '#{goal.title}' goal" %>">
      </form>
  <% elsif current_user && !(goal.cheered_by?(current_user)) && current_user.cheer_count > 0 %>
    <%= render "shared/cheer_button", goal: goal %>
  <% end %>
</li>

w7d5/practice-for-ch-rails-goal-app-refactor-main/app/views/shared/_user_form.html.erb
<% action = (type == :newuser) ? users_url : session_url %>
<% button_text = (type == :newuser) ? "Sign Up" : "Log In" %>

<form action="<%= action %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Username:
    <input type="text" value="<%= @user.username %>" name="user[username]">
  </label>
  <br>

  <label>Password:
    <input type="password" value="<%= @user.password %>" name="user[password]">
  </label>
  <br>

  <input type="submit" value="<%= button_text %>">
</form>